IMAGES = {
    "hero_pool": "https://images.unsplash.com/photo-1724688078741-6d89e587e809?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1Mjh8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBwb29sJTIwYXJjaGl0ZWN0dXJlfGVufDB8fHx8MTc4ODIyMTc3OXww&ixlib=rb-4.1.0&q=85",
    "manifesto": "https://images.unsplash.com/photo-1774535697396-53833f0587c4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwxfHxuYXR1cmFsJTIwc3RvbmUlMjBhcmNoaXRlY3R1cmFsJTIwd2FsbCUyMGNsYWRkaW5nfGVufDB8fHx8MTc4ODIyMTc2OXww&ixlib=rb-4.1.0&q=85",
    "texture": "https://images.pexels.com/photos/12606925/pexels-photo-12606925.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "bathroom": "https://images.unsplash.com/photo-1782805180061-3d131e792074?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHw0fHxkYXJrJTIwZ3JlZW4lMjBtYXJibGV8ZW58MHx8fHwxNzg4MjIxNzc5fDA&ixlib=rb-4.1.0&q=85",
    "pool_render": "https://images.unsplash.com/photo-1720110846280-737f9c7df86c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1Mjh8MHwxfHNlYXJjaHwzfHxsdXh1cnklMjBwb29sJTIwYXJjaGl0ZWN0dXJlfGVufDB8fHx8MTc4ODIyMTc3OXww&ixlib=rb-4.1.0&q=85",
    "green_marble": "https://images.unsplash.com/photo-1761498465939-716968017166?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHwzfHxkYXJrJTIwZ3JlZW4lMjBtYXJibGV8ZW58MHx8fHwxNzg4MjIxNzc5fDA&ixlib=rb-4.1.0&q=85",
}

PAGES = {
    "home": {
        "seo": {
            "title": "Sukabumi Green Stone Exporter | Pedra Bali — PT. Murfy Alam Indonesia",
            "description": "PT. Murfy Alam Indonesia exports premium Sukabumi Green Stone (Pedra Bali) pool tiles, wall cladding and paving to 40+ countries. Factory-direct natural stone from West Java, Indonesia.",
            "keywords": "sukabumi green stone, pedra bali, green stone pool tiles, indonesia natural stone exporter, bali green sukabumi, pool tile supplier",
        },
        "hero": {
            "overline": "INDONESIAN NATURAL STONE EXPORTER — EST. SUKABUMI, WEST JAVA",
            "line1": "SUKABUMI",
            "line2": "GREEN STONE",
            "line3": "FOR THE WORLD",
            "subheading": "Factory-direct Pedra Bali pool tiles, cladding and paving — quarried in West Java, calibrated to export standards, and shipped to architects, importers and resort developers in more than 40 countries.",
            "image": IMAGES["hero_pool"],
            "cta_primary": "Request a Quote",
            "cta_secondary": "Explore Products",
        },
        "marquee": ["PEDRA BALI", "SUKABUMI GREEN STONE", "VOLCANIC HERITAGE", "POOL TILES", "WALL CLADDING", "EXPORT QUALITY", "ZEOLITE INFUSED"],
        "manifesto": {
            "chapter": "01",
            "overline": "THE MATERIAL",
            "title": "Born of Volcanic Earth, Finished for the World's Finest Pools",
            "body1": "Sukabumi Green Stone — known across the trade as Pedra Bali — is a rare quartzite found only in the volcanic foothills of West Java, Indonesia. Its natural zeolite content subtly purifies pool water, while its emerald mineral structure turns sunlight into that unmistakable tropical glow.",
            "body2": "At PT. Murfy Alam Indonesia, we control the entire chain: quarry selection, precision cutting, grading, packing and export logistics. One partner, one standard, from our factory floor to your project site.",
            "image": IMAGES["manifesto"],
            "stats": [
                {"value": "15+", "label": "Years Exporting"},
                {"value": "40+", "label": "Countries Served"},
                {"value": "850+", "label": "Containers Shipped"},
            ],
        },
        "spotlight": {
            "chapter": "02",
            "overline": "SIGNATURE MATERIAL",
            "title": "Sukabumi Green Stone",
            "body": "The definitive pool stone of the tropics. Dense quartzite body, low water absorption, and a naturally slip-resistant surface — in the deep jade tone that made Bali's pools famous.",
            "image": IMAGES["green_marble"],
            "features": [
                {"title": "Natural Zeolite Content", "text": "Mineral zeolite within the stone helps adsorb impurities, keeping pool water clearer with less chemical load."},
                {"title": "Thermal Stability", "text": "Stays comfortable underfoot in extreme heat — from Maldives decks to Dubai rooftops."},
                {"title": "Slip Resistance", "text": "Naturally textured surface meets wet-area safety expectations for resorts and public pools."},
            ],
        },
        "applications": {
            "chapter": "03",
            "overline": "ARCHITECTURAL APPLICATIONS",
            "title": "One Stone, Every Surface",
            "items": [
                {"title": "Swimming Pools", "text": "Tiles, coping and mosaic for infinity pools, lagoons and Olympic facilities.", "image": IMAGES["hero_pool"]},
                {"title": "Wall Cladding", "text": "Split-face and honed panels for feature walls, facades and water features.", "image": IMAGES["manifesto"]},
                {"title": "Spa & Wellness", "text": "Thermal floors, hammam benches and wet-room surfaces.", "image": IMAGES["bathroom"]},
                {"title": "Decking & Paving", "text": "Sawn-cut pavers and stepping stones for landscape architecture.", "image": IMAGES["pool_render"]},
            ],
        },
        "values": {
            "chapter": "04",
            "overline": "WHY PARTNER WITH US",
            "title": "Built for B2B: Scale, Consistency, Trust",
            "items": [
                {"title": "Container-Scale Supply", "text": "From a single 20ft container to multi-container programs, our production lines are scheduled for export volume — not retail leftovers."},
                {"title": "QC at Every Cut", "text": "Each pallet is calibrated, graded and photographed before loading. You receive a full QC report with your shipping documents."},
                {"title": "Custom Dimensions", "text": "Any size from 10×10 cm mosaic to 60×120 cm slabs, bullnose coping and bespoke cuts — produced to your drawings."},
            ],
        },
        "parallax": {
            "image": IMAGES["texture"],
            "quote": "The green of Sukabumi is not a colour. It is a place.",
            "author": "— Architect's Notebook, Bali",
        },
        "global": {
            "chapter": "05",
            "overline": "GLOBAL EXPORT REACH",
            "title": "From West Java to Forty Countries",
            "body": "We ship FOB, CFR and CIF from Tanjung Priok Port, Jakarta, with full export documentation — phytosanitary, fumigation, certificate of origin and packing lists handled in-house.",
            "regions": ["Middle East", "Europe", "Southeast Asia", "Australia & Pacific", "Americas", "Africa"],
            "stats": [
                {"value": "40+", "label": "Export Countries"},
                {"value": "6", "label": "Continents"},
                {"value": "98%", "label": "On-Time Dispatch"},
            ],
        },
        "process": {
            "chapter": "06",
            "overline": "QUARRY TO DELIVERY",
            "title": "A Chain We Control End to End",
            "steps": [
                {"num": "01", "title": "Quarry Selection", "text": "Blocks are hand-selected at licensed Sukabumi quarries for colour consistency and density."},
                {"num": "02", "title": "Precision Cutting", "text": "Gang-saw and bridge cutters calibrated to ±1 mm tolerance across every batch."},
                {"num": "03", "title": "Quality Grading", "text": "Premium, standard and commercial grades are separated, labelled and photographed."},
                {"num": "04", "title": "Export Packing", "text": "Fumigated wooden crates, foam interleaving and container lashing to survive any voyage."},
                {"num": "05", "title": "Worldwide Logistics", "text": "Weekly sailings from Jakarta with tracked documentation and clearance support."},
            ],
        },
        "projects": {
            "chapter": "07",
            "overline": "SELECTED PROJECTS",
            "title": "Trusted by Resorts, Spas & Developers",
            "items": [
                {"title": "Cliff-Edge Infinity Pool", "location": "Uluwatu, Bali", "image": IMAGES["hero_pool"]},
                {"title": "Azure Spa Retreat", "location": "North Malé Atoll, Maldives", "image": IMAGES["bathroom"]},
                {"title": "Palm Villa Cladding", "location": "Dubai, UAE", "image": IMAGES["manifesto"]},
                {"title": "Hillside Lagoon Pool", "location": "Phuket, Thailand", "image": IMAGES["pool_render"]},
            ],
        },
        "testimonials": {
            "chapter": "08",
            "overline": "CLIENT VOICES",
            "title": "What Our Partners Say",
            "items": [
                {"quote": "The water colour we achieved with Murfy's Sukabumi tiles became the signature of our resort. Guests photograph it every single day.", "name": "Marco Bellini", "role": "Resort Developer, Maldives"},
                {"quote": "Twelve containers in eighteen months, and every pallet arrived calibrated exactly as graded. That consistency is rare in natural stone.", "name": "Sarah Nguyen", "role": "Procurement Director, Australia"},
                {"quote": "Pedra Bali transformed our spa project. The QC reports and packing quality made customs clearance effortless.", "name": "Hans Weber", "role": "Lead Architect, Germany"},
            ],
        },
        "faq": {
            "chapter": "09",
            "overline": "FREQUENTLY ASKED",
            "title": "Answers for Importers & Architects",
            "items": [
                {"q": "What is Sukabumi Green Stone?", "a": "Sukabumi Green Stone (trade name Pedra Bali) is a natural quartzite quarried exclusively in Sukabumi, West Java, Indonesia. It contains natural zeolite minerals that help purify pool water, and its emerald tone produces the iconic turquoise water effect seen in Bali's finest resort pools."},
                {"q": "What is the minimum order quantity (MOQ)?", "a": "Our standard MOQ is one 20ft container, approximately 350–400 m² depending on thickness. Mixed-product containers are welcome — you can combine tiles, coping and cladding in a single shipment."},
                {"q": "How long are production and shipping lead times?", "a": "Standard production takes 2–4 weeks from deposit. Sea freight adds 2–6 weeks depending on destination: roughly 1 week to Southeast Asia, 2–3 weeks to the Middle East and Australia, and 4–6 weeks to Europe and the Americas."},
                {"q": "What sizes and finishes are available?", "a": "Standard tiles: 10×10, 15×15, 20×20, 30×30, 30×60 and 60×60 cm, with bullnose coping and mosaic on mesh. Finishes include honed, sawn cut, rough face and split face. Custom dimensions are produced to your drawings."},
                {"q": "Do you provide samples?", "a": "Yes. We provide free 10×10 cm samples of current production lots — you only cover the courier cost. Sample kits ship within 3 working days via DHL or FedEx."},
                {"q": "Which port do you ship from, and under what terms?", "a": "We ship from Tanjung Priok Port, Jakarta, under FOB, CFR or CIF Incoterms. Full export documentation — invoice, packing list, certificate of origin, fumigation and phytosanitary certificates — is prepared in-house."},
            ],
        },
        "cta": {
            "title": "Let's Specify Your Next Project",
            "text": "Send us your drawings or quantities and receive a factory-direct quotation within 24 hours.",
            "button": "Request a Quote",
        },
    },
    "about": {
        "seo": {
            "title": "About Us | PT. Murfy Alam Indonesia — Sukabumi Green Stone Exporter",
            "description": "Learn about PT. Murfy Alam Indonesia: a factory-direct exporter of Sukabumi Green Stone (Pedra Bali) from West Java, Indonesia, serving importers and architects in 40+ countries.",
            "keywords": "about murfy alam indonesia, sukabumi stone factory, indonesia stone exporter company",
        },
        "hero": {
            "overline": "ABOUT PT. MURFY ALAM INDONESIA",
            "title": "Guardians of a Volcanic Legacy",
            "body": "From the quarries of Sukabumi to the world's most photographed pools — our story is carved in green stone.",
            "image": IMAGES["manifesto"],
        },
        "story": {
            "chapter": "01",
            "title": "Our Story",
            "paragraphs": [
                "PT. Murfy Alam Indonesia was founded in Sukabumi, West Java — the only place on Earth where true Pedra Bali is quarried. What began as a family workshop cutting pool tiles for local villas has grown into a fully integrated export operation serving importers, architects and resort developers across six continents.",
                "We remain factory-direct by principle. No traders, no middlemen: the people who select your blocks at the quarry are the same people who grade your pallets before loading. That is how we guarantee colour consistency, calibrated thickness and honest grading — container after container.",
            ],
            "image": IMAGES["texture"],
        },
        "values": {
            "chapter": "02",
            "title": "What We Stand For",
            "items": [
                {"title": "Integrity in Grading", "text": "Premium means premium. Every pallet is photographed and reported before it leaves our yard."},
                {"title": "Craft Over Volume", "text": "We would rather decline an order than ship stone we are not proud of."},
                {"title": "Long-Term Partnership", "text": "Most of our clients have reordered for five years or more. We build supply relationships, not transactions."},
            ],
        },
        "stats": [
            {"value": "15+", "label": "Years in Operation"},
            {"value": "120+", "label": "Skilled Craftsmen"},
            {"value": "850+", "label": "Containers Exported"},
            {"value": "40+", "label": "Countries Served"},
        ],
        "quarry": {
            "chapter": "03",
            "title": "The Sukabumi Quarry",
            "body": "Our concession sits in the volcanic belt of West Java, where ancient geothermal activity infused quartzite with zeolite and the green chlorite minerals that define Pedra Bali. Blocks are extracted in limited campaigns to protect both colour consistency and the surrounding watershed.",
            "image": IMAGES["green_marble"],
            "bullets": ["Licensed & audited quarry operations", "Water-recycling cutting lines", "Reforestation program around the concession", "Fair-wage employment for local communities"],
        },
        "certifications": {
            "chapter": "04",
            "title": "Compliance & Documentation",
            "items": [
                {"title": "Export Licensed", "text": "Registered Indonesian exporter with full legal mining and trading documentation."},
                {"title": "ISPM-15 Packing", "text": "Fumigated, stamped wooden crates accepted at every major port worldwide."},
                {"title": "Lab-Tested Stone", "text": "Density, absorption and slip-resistance test reports available per production lot."},
            ],
        },
        "cta": {"title": "Meet Your Factory Partner", "text": "Visit our yard in Sukabumi or schedule a video call with our export team.", "button": "Contact Us"},
    },
    "contact": {
        "seo": {
            "title": "Contact Us | PT. Murfy Alam Indonesia — Request a Stone Quote",
            "description": "Contact PT. Murfy Alam Indonesia for Sukabumi Green Stone quotations, samples and export inquiries. Response within 24 hours, WhatsApp available.",
            "keywords": "sukabumi green stone quote, pedra bali supplier contact, indonesia stone exporter contact",
        },
        "hero": {
            "overline": "CONTACT & QUOTATION",
            "title": "Tell Us About Your Project",
            "body": "Share your drawings, quantities or simply an idea — our export team replies within 24 hours on business days.",
        },
        "info": {
            "address": "Sukabumi, West Java, Indonesia",
            "phone": "+62 851-4156-7350",
            "whatsapp": "6285141567350",
            "email": "giat@zeofa.com",
            "hours": "Monday – Saturday, 08:00 – 17:00 (GMT+7)",
        },
        "form": {"title": "Request a Quotation", "text": "All fields marked * are required. Attachments can be shared later by email or WhatsApp."},
        "faq": {
            "title": "Before You Write",
            "items": [
                {"q": "How fast will you reply?", "a": "Within 24 hours on business days — usually much faster via WhatsApp."},
                {"q": "Can I get a price list?", "a": "Yes. Tell us your destination port and target quantities and we will send our current export price list."},
                {"q": "Do you handle small trial orders?", "a": "Trial orders below one container are possible for sample verification — ask our team about LCL options."},
            ],
        },
    },
}

PRODUCTS = [
    {
        "name": "Sukabumi Green Stone Tiles",
        "slug": "sukabumi-green-stone-tiles",
        "category": "Pool Tiles",
        "short_desc": "The signature Pedra Bali pool tile — zeolite-rich quartzite in deep jade green.",
        "description": "Our flagship Sukabumi Green Stone tiles are cut from premium selected blocks and calibrated to export tolerance. The stone's natural zeolite content helps keep pool water crystal clear, while its mineral structure creates the luminous turquoise effect that made Bali pools world-famous. Suitable for submerged and deck applications in any climate.",
        "image": IMAGES["green_marble"],
        "gallery": [IMAGES["green_marble"], IMAGES["hero_pool"], IMAGES["texture"]],
        "finishes": ["Honed", "Sawn Cut", "Rough Face"],
        "sizes": ["10×10 cm", "15×15 cm", "20×20 cm", "30×30 cm", "30×60 cm", "60×60 cm", "Custom to drawing"],
        "applications": ["Swimming Pools", "Spa & Wellness", "Water Features", "Bathroom Walls"],
        "featured": True,
        "seo_title": "Sukabumi Green Stone Tiles — Pedra Bali Pool Tiles Exporter",
        "seo_desc": "Premium Sukabumi Green Stone pool tiles (Pedra Bali) direct from the Indonesian factory. Honed, sawn and rough finishes, 10×10 to 60×60 cm, container export worldwide.",
    },
    {
        "name": "Pedra Hijau Green Sukabumi",
        "slug": "pedra-hijau-green-sukabumi",
        "category": "Pool Tiles",
        "short_desc": "The lighter 'hijau muda' grade — bright emerald tone for vivid water colour.",
        "description": "Pedra Hijau is the lighter emerald grade of Sukabumi Green Stone, prized by architects who want a brighter, more saturated water colour. Quarried from the same volcanic belt and processed on the same lines, it offers identical density and zeolite benefits with a distinctly fresher tone.",
        "image": IMAGES["hero_pool"],
        "gallery": [IMAGES["hero_pool"], IMAGES["pool_render"]],
        "finishes": ["Honed", "Sawn Cut"],
        "sizes": ["10×10 cm", "20×20 cm", "30×30 cm", "30×60 cm", "Custom to drawing"],
        "applications": ["Swimming Pools", "Plunge Pools", "Lagoons"],
        "featured": True,
        "seo_title": "Pedra Hijau Green Sukabumi Tiles — Bright Emerald Pool Stone",
        "seo_desc": "Pedra Hijau (light green Sukabumi) pool tiles exported worldwide. Bright emerald tone, natural zeolite, factory-direct from West Java, Indonesia.",
    },
    {
        "name": "Green Stone Pool Coping & Bullnose",
        "slug": "green-stone-pool-coping-bullnose",
        "category": "Coping & Edging",
        "short_desc": "Bullnose and square-edge coping profiles for pool perimeters and steps.",
        "description": "Precision-milled Sukabumi Green Stone coping in bullnose, half-bullnose and drop-face profiles. Each piece is cut to your radius or straight-run drawings, numbered and dry-laid for photo approval before packing — so installation on site is fast and flawless.",
        "image": IMAGES["pool_render"],
        "gallery": [IMAGES["pool_render"], IMAGES["hero_pool"]],
        "finishes": ["Honed", "Sawn Cut", "Bullnose Edge", "Drop Face"],
        "sizes": ["30×60 cm", "40×80 cm", "Custom radius", "Custom to drawing"],
        "applications": ["Pool Perimeters", "Steps & Treads", "Spa Edges"],
        "featured": True,
        "seo_title": "Sukabumi Green Stone Pool Coping — Bullnose Edge Exporter",
        "seo_desc": "Bullnose and drop-face pool coping in Sukabumi Green Stone, cut to your drawings and exported in containers from Indonesia.",
    },
    {
        "name": "Sukabumi Green Mosaic (Mesh)",
        "slug": "sukabumi-green-mosaic-mesh",
        "category": "Mosaic",
        "short_desc": "Mesh-mounted mosaic sheets for curves, steps, benches and infinity edges.",
        "description": "Mesh-mounted Sukabumi Green Stone mosaic in 25×25, 50×50 and hexagonal patterns. Ideal for curved walls, spa benches, steps and vanishing edges where full-size tiles cannot follow the geometry. Sheets are interleaved and crate-packed for export.",
        "image": IMAGES["texture"],
        "gallery": [IMAGES["texture"], IMAGES["bathroom"]],
        "finishes": ["Honed", "Split Face"],
        "sizes": ["25×25 mm on mesh", "50×50 mm on mesh", "Hexagonal", "Sheet 30×30 cm"],
        "applications": ["Curved Walls", "Spa Benches", "Infinity Edges", "Steps"],
        "featured": False,
        "seo_title": "Sukabumi Green Stone Mosaic Sheets — Mesh Mounted Exporter",
        "seo_desc": "Mesh-mounted Sukabumi Green Stone mosaic for curved pools, spa benches and infinity edges. Export quality from PT. Murfy Alam Indonesia.",
    },
    {
        "name": "Black Lava Stone (Pedra Hitam)",
        "slug": "black-lava-stone-pedra-hitam",
        "category": "Cladding & Paving",
        "short_desc": "Volcanic basalt for dramatic cladding, paving and pool contrast bands.",
        "description": "Indonesian black lava stone — a dense volcanic basalt with a fine, even grain. Architects specify it as a dramatic counterpoint to green Sukabumi waterlines, and as a hard-wearing surface for driveways, facades and garden walls.",
        "image": IMAGES["manifesto"],
        "gallery": [IMAGES["manifesto"], IMAGES["texture"]],
        "finishes": ["Honed", "Sawn Cut", "Split Face", "Rough Face"],
        "sizes": ["20×40 cm", "30×60 cm", "40×80 cm", "60×60 cm", "Custom to drawing"],
        "applications": ["Wall Cladding", "Paving & Driveways", "Pool Contrast Bands", "Facades"],
        "featured": False,
        "seo_title": "Black Lava Stone Indonesia — Pedra Hitam Cladding Exporter",
        "seo_desc": "Indonesian black lava stone (Pedra Hitam) for cladding and paving, container export from West Java. Honed, sawn and split-face finishes.",
    },
    {
        "name": "Andesite Grey Stone",
        "slug": "andesite-grey-stone",
        "category": "Cladding & Paving",
        "short_desc": "Fine-grained grey volcanic stone for contemporary decks and facades.",
        "description": "Andesite is Indonesia's premium grey volcanic stone — extremely dense, low-absorption and consistent in tone. A favourite for contemporary pool decks, public plazas and ventilated facades where a cool grey palette complements green Sukabumi water.",
        "image": IMAGES["bathroom"],
        "gallery": [IMAGES["bathroom"], IMAGES["manifesto"]],
        "finishes": ["Honed", "Flamed", "Sawn Cut"],
        "sizes": ["30×60 cm", "40×80 cm", "60×60 cm", "60×120 cm", "Custom to drawing"],
        "applications": ["Pool Decks", "Public Paving", "Ventilated Facades", "Stairs"],
        "featured": False,
        "seo_title": "Andesite Grey Stone Indonesia — Deck & Facade Exporter",
        "seo_desc": "Grey andesite stone tiles and slabs from Indonesia for pool decks, paving and facades. Dense, low absorption, export packed worldwide.",
    },
]

POSTS = [
    {
        "title": "Why Sukabumi Green Stone Is the World's Favourite Pool Tile",
        "slug": "why-sukabumi-green-stone-world-favourite-pool-tile",
        "excerpt": "From Bali's first boutique resorts to five-star pools in Dubai and the Maldives — how one volcanic quartzite became the global standard for luxury pool interiors.",
        "content": "Walk up to almost any iconic resort pool in Southeast Asia and you are looking at Sukabumi Green Stone. The trade calls it Pedra Bali, but the stone comes from one place only: the volcanic foothills around Sukabumi, West Java.\n\nIts secret is mineralogical. The quartzite body is infused with zeolite, a natural molecular sieve that adsorbs impurities from water, and with chlorite minerals that give the stone its signature jade tone. Sunlight filtering through water above the stone produces the luminous turquoise that photographers — and guests — cannot resist.\n\nBeyond beauty, the stone performs. Water absorption below 0.4% means it survives freeze-thaw cycles and aggressive pool chemistry. Its naturally textured surface provides slip resistance without coatings. And because it is a true quartzite, it outlasts ceramic and glass alternatives by decades.\n\nFor importers and architects, the message is simple: when the brief says 'Bali pool green', there is only one original. Specify Sukabumi Green Stone, and specify it factory-direct.",
        "image": IMAGES["hero_pool"],
        "author": "Export Team, PT. Murfy Alam Indonesia",
        "tags": ["Sukabumi Green Stone", "Pool Design", "Architecture"],
        "published": True,
        "seo_title": "Why Sukabumi Green Stone Is the World's Favourite Pool Tile",
        "seo_desc": "The mineralogy and history behind Pedra Bali — the zeolite-rich green quartzite from Sukabumi, Indonesia, used in the world's finest resort pools.",
    },
    {
        "title": "Pedra Bali vs. Ordinary Pool Tiles: What Architects Should Know",
        "slug": "pedra-bali-vs-ordinary-pool-tiles-architect-guide",
        "excerpt": "Ceramic, glass mosaic or natural quartzite? A technical comparison of absorption, slip resistance, thermal behaviour and lifecycle cost for pool interiors.",
        "content": "Pool interior materials are usually compared on colour and price. That is a mistake. The real specification criteria are absorption, slip resistance, thermal behaviour and lifecycle cost.\n\nAbsorption: glazed ceramics rely on their glaze; once crazed, the body absorbs water and fails. Sukabumi Green Stone absorbs less than 0.4% through the entire body — no glaze to fail.\n\nSlip resistance: most glass mosaics are dangerously smooth when biofilm forms. Natural quartzite texture maintains grip without applied coatings.\n\nThermal behaviour: dark ceramics on decks become untouchable in tropical sun. Sukabumi stone stays noticeably cooler thanks to its mineral structure and thermal mass.\n\nLifecycle cost: a natural stone pool interior routinely serves 25+ years. Ceramic and mosaic alternatives typically need resurfacing within 8–12. Across a resort's operating life, Pedra Bali is the economical choice — before you count its marketing value as the most photographed surface on the property.",
        "image": IMAGES["pool_render"],
        "author": "Technical Desk, PT. Murfy Alam Indonesia",
        "tags": ["Specification", "Pedra Bali", "Materials"],
        "published": True,
        "seo_title": "Pedra Bali vs Ordinary Pool Tiles — Architect's Specification Guide",
        "seo_desc": "Technical comparison of Sukabumi Green Stone vs ceramic and glass pool tiles: absorption, slip resistance, thermal comfort and lifecycle cost.",
    },
    {
        "title": "From Quarry to Container: How We Export Natural Stone Worldwide",
        "slug": "quarry-to-container-natural-stone-export-process",
        "excerpt": "A transparent look at our five-stage export chain — block selection, precision cutting, grading, ISPM-15 packing and documented worldwide logistics.",
        "content": "International buyers often ask what 'factory-direct' really means. Here is our complete chain, step by step.\n\nStage one — quarry selection. Our supervisors hand-select blocks at licensed Sukabumi quarries, rejecting anything with unstable colour or micro-fractures before it reaches the saw.\n\nStage two — precision cutting. Gang saws and bridge cutters calibrated to ±1 mm produce your tiles, coping or cladding to drawing.\n\nStage three — grading. Every piece is graded premium, standard or commercial, then labelled and photographed. Your QC report is compiled pallet by pallet.\n\nStage four — export packing. ISPM-15 fumigated crates, foam interleaving and professional container lashing protect the stone across any voyage.\n\nStage five — logistics. Weekly sailings from Tanjung Priok, Jakarta, under FOB, CFR or CIF terms, with complete documentation handled in-house. From our yard to your port, one partner is accountable: us.",
        "image": IMAGES["manifesto"],
        "author": "Logistics Desk, PT. Murfy Alam Indonesia",
        "tags": ["Export", "Logistics", "Quality Control"],
        "published": True,
        "seo_title": "From Quarry to Container — Indonesian Natural Stone Export Process",
        "seo_desc": "Inside PT. Murfy Alam Indonesia's five-stage export chain for Sukabumi Green Stone: selection, cutting, grading, packing and worldwide shipping.",
    },
    {
        "title": "Caring for Green Stone Pools: A Maintenance Guide for Resorts",
        "slug": "caring-for-green-stone-pools-maintenance-guide-resorts",
        "excerpt": "How to keep a Sukabumi Green Stone pool interior pristine for decades — water chemistry targets, cleaning routines and what to avoid.",
        "content": "A Sukabumi Green Stone pool is a 25-year asset. Protecting it is simple if your team follows a few rules.\n\nWater chemistry first: keep pH between 7.2 and 7.6 and avoid aggressive acid washing. The stone's zeolite content actively supports water clarity, so most operators find they can reduce clarifier dosing.\n\nCleaning: brush the waterline weekly to prevent scale and biofilm. For calcium deposits, use diluted, stone-safe descalers — never muriatic acid at full strength, and always test a small area first.\n\nWhat to avoid: high-pressure washers above 150 bar on honed finishes, metal brushes, and any sealer not rated for submerged natural stone. In most submerged applications, sealing is unnecessary — the stone is dense enough.\n\nFollow these basics and the stone will outlast the resort's first renovation cycle — and look better with every passing season.",
        "image": IMAGES["bathroom"],
        "author": "Technical Desk, PT. Murfy Alam Indonesia",
        "tags": ["Maintenance", "Resorts", "Pool Care"],
        "published": True,
        "seo_title": "Green Stone Pool Maintenance Guide for Resorts — Sukabumi Care",
        "seo_desc": "Resort maintenance guide for Sukabumi Green Stone pools: water chemistry targets, safe cleaning routines and products to avoid.",
    },
]
